### ISSUE TITLE
Challenge with calling python3 draw_phylo.py phyml_tree.txt

### ISSUE THREAD

**Issue by ssyamoako** [vappiah/phylogenetic-trees#1]
Traceback (most recent call last):
  File "draw_phylo.py", line 20, in <module>
    Phylo.draw(tree,do_show=False)
  File "/home/gyrp/share/Sun_28_feb_21/Practice/phylo/lib/python3.8/site-packages/Bio/Phylo/_utils.py", line 501, in draw
    fig = plt.figure()
  File "/home/gyrp/share/Sun_28_feb_21/Practice/phylo/lib/python3.8/site-packages/matplotlib/pyplot.py", line 687, in figure
    figManager = new_figure_manager(num, figsize=figsize,
  File "/home/gyrp/share/Sun_28_feb_21/Practice/phylo/lib/python3.8/site-packages/matplotlib/pyplot.py", line 315, in new_figure_manager
    return _backend_mod.new_figure_manager(*args, **kwargs)
  File "/home/gyrp/share/Sun_28_feb_21/Practice/phylo/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 3494, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/home/gyrp/share/Sun_28_feb_21/Practice/phylo/lib/python3.8/site-packages/matplotlib/backends/_backend_tk.py", line 885, in new_figure_manager_given_figure
    window = tk.Tk(className="matplotlib")
  File "/home/gyrp/miniconda3/lib/python3.8/tkinter/_init_.py", line 2261, in init
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display "localhost:0.0"Traceback (most recent call last):
  File "draw_phylo.py", line 20, in <module>
    Phylo.draw(tree,do_show=False)
  File "/home/gyrp/share/Sun_28_feb_21/Practice/phylo/lib/python3.8/site-packages/Bio/Phylo/_utils.py", line 501, in draw
    fig = plt.figure()
  File "/home/gyrp/share/Sun_28_feb_21/Practice/phylo/lib/python3.8/site-packages/matplotlib/pyplot.py", line 687, in figure
    figManager = new_figure_manager(num, figsize=figsize,
  File "/home/gyrp/share/Sun_28_feb_21/Practice/phylo/lib/python3.8/site-packages/matplotlib/pyplot.py", line 315, in new_figure_manager
    return _backend_mod.new_figure_manager(*args, **kwargs)
  File "/home/gyrp/share/Sun_28_feb_21/Practice/phylo/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 3494, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/home/gyrp/share/Sun_28_feb_21/Practice/phylo/lib/python3.8/site-packages/matplotlib/backends/_backend_tk.py", line 885, in new_figure_manager_given_figure
    window = tk.Tk(className="matplotlib")
  File "/home/gyrp/miniconda3/lib/python3.8/tkinter/_init_.py", line 2261, in init
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display "localhost:0.0"
![Capture](https://user-images.githubusercontent.com/51422644/109627236-4e2f3100-7b39-11eb-9858-75e74bff3685.PNG)

**Comment by vappiah** [comment]
@ssyamoako The error message indicates that the library Biopython was not installed.  To begin the analysis, you have to first install all the tools by running the script _download_tools.sh_
I have also modified the python script so redownload the entire repository and do the analysys again. Let me know how it goes.

**Comment by ssyamoako** [comment]
i have installed it but still

**Comment by ssyamoako** [comment]
I am using an online tool repl.it and i have everything done just want to know how to save the images to.
![2Capture](https://user-images.githubusercontent.com/51422644/109634181-d82ec800-7b40-11eb-97e8-641c1eae8eb9.PNG)

**Comment by vappiah** [comment]
> I am using an online tool repl.it and i have everything done just want to know how to save the images to.

Ok. that explains the error. The script was designed to run locally on a computer. It saves the matplotlib in your current directory.
Since its an online tool, I will suggest you do this
-  comment out the lines  _pylab.savefig('Phylo.jpg',dpi=1500)_  _pylab.savefig('Phylo.svg',dpi=1500)_
-  change this code _Phylo.draw(tree,do_show=False)_ to Phylo.draw(tree,do_show=True)

**Comment by ssyamoako** [comment]
Thank you. It worked perfectly. but is it possible i can change the directory and save the image even as i am working online.

**Comment by ssyamoako** [comment]
I was able to save the image and cp it from it directory to my working directly.... the only issue is it wasn't saved in svg but rather png
![aa](https://user-images.githubusercontent.com/51422644/109677187-54410400-7b71-11eb-9ce6-f1ab8d8b9427.jpg)

**Comment by vappiah** [comment]
OK Nice.

The reason why svg format was absent is because we commented out the lines doing the saving. If you know the full path of your directory , then you can uncomment those lines and modify the script as follows

__import os
workingdir=os.getcwd()
_pylab.savefig('%s/Phylo.jpg'%workingdir,dpi=1500)_ 
_pylab.savefig('%s/Phylo.svg'%workingdir,dpi=1500)___


I can't guarantee if this will work but you can give it a try.

**Note:** The scripts were written to be run on a local machine so if you want additional functionalities due to the use of an online python interpretor, then you have to explore those ways.

**Comment by ssyamoako** [comment]
Alright i will try it out. thank you
